config/routes.rb
Rails.application.routes.draw do
  resources :drinkers
  resources :bottles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle.rb
class Bottle < ApplicationRecord
    belongs_to :drinker
end

app/models/drinker.rb
class Drinker < ApplicationRecord
    has_many :bottles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drinkers_controller.rb
class DrinkersController < ApplicationController

    require 'faker'

    def index
        @drinkers = Drinker.all
    end

    def show
        @drinker = Drinker.find(params[:id])
    end

    def new
        @drinker = Drinker.new   
    end

    def create
        @drinker = Drinker.create(drinker_params)
        redirect_to drinkers_path(@drinker)
    end

    def edit
        @drinker = Drinker.find(params[:id])
    end

    def update
        @drinker = Drinker.find(params[:id])
        @drinker.update(drinker_params)

        redirect_to @drinker
    end

    def destroy
        @drinker = Drinker.find(params[:id])
        @drinker.destroy

        redirect_to drinkers_path
    end

    private

    def drinker_params
        params.require(:drinker).permit(:name, :goal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinkers_helper.rb
module DrinkersHelper
end

app/views/drinkers/edit.html.erb
<div class="container" style="padding-top: 30px;">
    <h1 class="display-3" style="padding-top: 30px;">Edit Drinker's Page</h1>
    <br/>
    <p>Made a boo-boo? Change your profile using this form. </p>
</div>

<div class="container" style="padding-top: 30px;">
    <%= form_for @drinker do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :goal %>
    <%= f.text_field :goal %>

    <%= f.submit %>
    <% end %>

    <%= button_to "Delete", drinker_path(@drinker), method: :delete %>

</div>

app/views/drinkers/index.html.erb
<h2 class="display-3" style="padding-top: 30px;">Who's Drinking?</h2>

<div class="container">
    <div class="row row-cols-2">

        <div class="col">
            <h2 style="padding: 15px;">Featured Drinker: Pikachu</h2>
            <div style="padding: 20px;"><%= image_tag "pikawater.jpeg" %></div>
            <p>A sturdy little ball electricity with a mighty thirst, Pikachu always achieves his #DRANK goals. </p>
        </div>

        <div class="col"> 
            <ul style= "list-style-type: none;">
                <% @drinkers.each do |drinker| %>
                <li style="padding-top: 20px;"><h6><%= link_to drinker.name, drinker %>, <%= drinker.goal %></h6></li>
                <% end %>
            </ul>
        </div>

    </div>
</div>

<div class="container" style="padding-top: 30px;">
    <h3>Want to join the #DRANK challenge? Join <%= link_to "here.", "/drinkers/new" %></h3>
</div>

app/views/drinkers/new.html.erb
<div class="container" style="padding-top: 30px;">
    <h1 class="display-3" style="padding-top: 30px;">New Drinker's Form</h1>
    <br/>
    <p>Wanna #DRANK? Add yourself to our database using this form. </p>
</div>

<div class="container" style="padding-top: 30px;">
    <%= form_for @drinker do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>


    <%= f.label :goal %>
    <%= f.text_field :goal %>

    <%= f.submit %>
    <% end %>
</div>

app/views/drinkers/show.html.erb
<div class="container">
    <h1 class="display-3" style="padding-top: 30px;"><%= @drinker.name %></h1>
    <br/>
</div>

<div class="container">
    <h1 class="display-6"><%= @drinker.goal %></h1>
    <br>
    <p>Dolores quis quia ad quo voluptates. Maxime delectus totam numquam. Necessitatibus vel atque qui dolore. Id neque nemo. Dolores iusto facere est ad. Accusamus ipsa dolor ut. Et officiis ut hic. Sunt asperiores minus distinctio debitis ipsa dolor. Minima eos deleniti.</p>
</div>

<div class="container" style="padding-top: 50px;">
    <p>Learn about another #DRANK Challenger participant, <%= link_to "here.", "/drinkers" %></p>
    <p>To edit your file, click <%= link_to "here.", edit_drinker_path(@drinker) %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>#DRANK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
          <a class="navbar-brand" href="/drinkers">#DRANK</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

              <li class="nav-item active">
                <a class="nav-link" href="/drinkers">Water Drinkers</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/bottles/new">Add Water</a>
              </li>

            </ul>
          </div>
        </nav>

    <%= yield %>
  </body>
</html>